import bcrypt from 'bcryptjs';

const data = {

    users: [
        {
            name:'Cesar',
            email: 'cesarn@supertiernos.com',
            password: bcrypt.hashSync('usertest', 8),
            isAdmin: true,
        },
        {
            name:'Alana',
            email: 'alanac@supertiernos.com',
            password: bcrypt.hashSync('usertest', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name:'Capa impermeable para perros pequeño',
            category:'Perros',
            image: '/images/p1.jpg',
            price:'80000',
            countInStock: 12,
            brand: 'Super Tiernos',
            rating:1.5,
            numReviews:7,
            description:'Protegelos de la lluvia',
        },
        {
            name:'Capa impermeable para perros grande',
            category:'Perros',
            image: '/images/p2.jpg',
            price:'100000',
            countInStock: 9,
            brand: 'Super Tiernos',
            rating:2.5,
            numReviews:8,
            description:'Protegelos de la lluvia. Talla grande',
        },
        {
            name:'Hueso grande y pequeño',
            category:'Perros',
            image: '/images/p3.jpg',
            price:'15000',
            countInStock: 0,
            brand: 'Super Tiernos',
            rating:3.5,
            numReviews:9,
            description:'para sus dientes',
        },
        {
            name:'Pelota Gato',
            category:'Gatos',
            image: '/images/p4.jpg',
            price:'18000',
            countInStock: 1,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'La mejor diversion Gatuna',
        },
        {
            name:'Juguete Mostacho',
            category:'Perros',
            image: '/images/p5.jpg',
            price:'30000',
            countInStock: 2,
            brand: 'Super Tiernos',
            rating:5,
            numReviews:10,
            description:'Se diverte el y te ries tu',
        },
        {
            name:'Vitamina Moloc',
            category:'Perros',
            image: '/images/p1.jpg',
            price:'15000',
            countInStock: 20,
            brand: 'Biotec',
            rating:5,
            numReviews:7,
            description:'Vitaminas para perritos',
        },
    ],
};
export default data;