const data = {
    products: [
        {
            _id:'1',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p1.jpg',
            price:80000,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'Protegelos de la lluvia',
        },
        {
            _id:'2',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p2.jpg',
            price:100000,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'Protegelos de la lluvia. Talla grande',
        },
        {
            _id:'3',
            name:'Hueso grande y pequeño',
            category:'Perros',
            image: '/images/p3.jpg',
            price:15000,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'para sus dientes',
        },
        {
            _id:'4',
            name:'Pelota Gato',
            category:'Gatos',
            image: '/images/p4.jpg',
            price:18000,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'La mejor diversion Gatuna',
        },
        {
            _id:'5',
            name:'Juguete Mostacho',
            category:'Perros',
            image: '/images/p5.jpg',
            price:30000,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'Se diverte el y te ries tu',
        },
    ],
};
export default data;