const data = {
    products: [
        {
            _id:'1',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p1.jpg',
            price:'80,000',
            countInStore: 12,
            brand: 'Super Tiernos',
            rating:1.5,
            numReviews:7,
            description:'Protegelos de la lluvia',
        },
        {
            _id:'2',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p2.jpg',
            price:'100,000',
            countInStore: 9,
            brand: 'Super Tiernos',
            rating:2.5,
            numReviews:8,
            description:'Protegelos de la lluvia. Talla grande',
        },
        {
            _id:'3',
            name:'Hueso grande y pequeño',
            category:'Perros',
            image: '/images/p3.jpg',
            price:'15,000',
            countInStore: 0,
            brand: 'Super Tiernos',
            rating:3.5,
            numReviews:9,
            description:'para sus dientes',
        },
        {
            _id:'4',
            name:'Pelota Gato',
            category:'Gatos',
            image: '/images/p4.jpg',
            price:'18,000',
            countInStore: 1,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'La mejor diversion Gatuna',
        },
        {
            _id:'5',
            name:'Juguete Mostacho',
            category:'Perros',
            image: '/images/p5.jpg',
            price:'30,000',
            countInStore: 2,
            brand: 'Super Tiernos',
            rating:5,
            numReviews:10,
            description:'Se diverte el y te ries tu',
        },
        {
            _id:'6',
            name:'Suplementos Perros',
            category:'Perros',
            image: '/images/p3.jpg',
            price:'120,000',
            countInStore: 20,
            brand: 'Super Tiernos',
            rating:5,
            numReviews:23,
            description:'Se diverte el y te ries tu',
        },
    ],
};
export default data;